<?php
// module/Album/view/cookbookadm/cookbookadm/delete.phtml:
/*
 * В этом скрипте отображается сообщение с подтверждением для пользователя, а затем форма с кнопками «Да» и «Нет».
 *  В действии мы специально проверяли значение «Да» при выполнении удаления.
 */
$title = 'Delete recept';
$url   = $this->url('cookbookadm', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete recept
    "<?= $this->escapeHtml($cookbookadm->name) ?>"
    with sostav:
    "<?= $this->escapeHtml($cookbookadm->sostav) ?>" ?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $cookbookadm->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>